-- In KEYCLOAKPDB, as SYSDBA: tablespace, a schema-only OWNER (no login) that will hold every Keycloak
-- object, and a separate APPLICATION user (CREATE SESSION only) that Keycloak connects as, mirroring FHIRPDB.
--   @40-keycloak-user.sql <OWNER> <APP_USER> <APP_PASSWORD>
-- No tables are created here: Keycloak's schema is generated by Keycloak itself (manual migration strategy)
-- and applied as the owner by idp/db-migrate.sh, which then reruns 25-grants-and-synonyms.sql.
set verify off feedback on
whenever sqlerror exit failure rollback

define owner = &1
define app = &2
define app_pwd = &3

alter session set db_create_file_dest = '/opt/oracle/oradata';
create tablespace poc_keycloak_data datafile size 128m autoextend on next 64m maxsize 2g;

create user &owner no authentication
  default tablespace poc_keycloak_data
  temporary tablespace temp
  quota unlimited on poc_keycloak_data;

create user &app identified by "&app_pwd"
  default tablespace poc_keycloak_data
  temporary tablespace temp;
grant create session to &app;

exit;
