#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# bootstrap.sh -- starts the POC stack (compose project spezi-poc).
# Adapted from the governance project's bin/bootstrap.sh.
#
# First time (db/.initialized absent):
#   1. Ensures credentials exist (db/make-env.sh, never overwrites)
#   2. Starts oracle (healthy), then runs oracle-init to completion (PDBs, users, HAPI schema)
#   3. Fails fast if the init did not exit 0
#   4. Removes the exited init container so no inactive service lingers
#   5. Loads Keycloak's schema into KEYCLOAKPDB (idp/db-migrate.sh): Keycloak must not start before it exists
#   6. Starts the rest of the stack and writes the db/.initialized marker
#
# Later runs (marker present): oracle first, then idp/db-migrate.sh (idempotent: a no-op once the schema is
# loaded), then plain `up -d`; the init service is not even in play.
#
# To reinitialize without losing data: remove db/.initialized and rerun (the init is
# idempotent). To start from nothing: scripts/reset.sh.
# UNTESTED until you run it.
# ---------------------------------------------------------------------------
set -euo pipefail

RUN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MARKER_FILE="${RUN_DIR}/db/.initialized"
COMPOSE_CMD="${RUN_DIR}/scripts/compose.sh"
INIT_CONTAINER=spezi-poc-oracle-init

log()  { echo "✅ $*"; }
fail() { echo "❌ ERROR: $*" >&2; exit 1; }

assert_docker_running() {
  if ! docker info > /dev/null 2>&1; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
      echo "Starting Docker Desktop..."
      open -a Docker
      until docker info > /dev/null 2>&1; do sleep 2; done
      echo "Docker Desktop ready."
    else
      fail "Docker daemon is not running"
    fi
  fi
}

wait_for_oracle() {
  local i
  for i in $(seq 1 90); do
    [ "$(docker inspect -f '{{.State.Health.Status}}' spezi-poc-oracle 2>/dev/null)" = "healthy" ] && return 0
    sleep 5
  done
  fail "oracle did not become healthy"
}

# Keycloak's schema is generated by Keycloak itself and loaded as the schema owner. It must exist before Keycloak
# starts, so this runs between oracle and the rest of the stack. The Keycloak image is built here (it carries the
# Oracle JDBC driver; the first build downloads two jars, verified against pinned SHA-256 checksums).
migrate_keycloak_schema() {
  log "Keycloak image and schema ..."
  ${COMPOSE_CMD} build keycloak
  "${RUN_DIR}/idp/db-migrate.sh"
}

run_initialize() {
  log "Project spezi-poc is not initialized. Running with the *initialize* profile ..."

  # Oracle first (and, via depends_on, nothing else): the init needs it healthy, Keycloak's schema needs the init.
  ${COMPOSE_CMD} --profile initialize up -d --build oracle oracle-init || {
    echo "---- last lines of the init container log:" >&2
    docker logs --tail 40 "${INIT_CONTAINER}" >&2 || true
    fail "startup failed; fix the cause, then rerun (the init is idempotent)."
  }

  # Block until the init container exits, then check how.
  local exit_code
  exit_code=$(docker wait "${INIT_CONTAINER}")
  if [ "${exit_code}" != "0" ]; then
    docker logs --tail 40 "${INIT_CONTAINER}" >&2 || true
    fail "Init container '${INIT_CONTAINER}' exited with code ${exit_code}."
  fi
  log "${INIT_CONTAINER} completed successfully."

  # Remove the exited init container so no inactive service lingers.
  ${COMPOSE_CMD} --profile initialize rm -f oracle-init > /dev/null

  migrate_keycloak_schema

  ${COMPOSE_CMD} up -d --build
  touch "${MARKER_FILE}"
  log "Initialization complete. Marker file written: ${MARKER_FILE}"
}

run_initialized() {
  log "Project spezi-poc is initialized. Starting services ..."
  ${COMPOSE_CMD} up -d --build oracle
  wait_for_oracle
  migrate_keycloak_schema
  ${COMPOSE_CMD} up -d --build
}

assert_docker_running

# create gitignored credentials where absent (never overwrites)
"${RUN_DIR}/db/make-env.sh"
"${RUN_DIR}/idp/make-env.sh"

# create the local CA and the HAPI, proxy and Keycloak certificates where absent (idempotent; keys live outside the repo)
"${RUN_DIR}/scripts/make-tls.sh"

if [ -f "${MARKER_FILE}" ]; then
  run_initialized
else
  run_initialize
fi

log "spezi-poc is up. Verify with: make stack-verify"
