-- Hibernate 6.4.10 global temporary "id tables" (HTE_*) used by HAPI FHIR 7.6.0 on Oracle for
-- multi-table bulk updates/deletes. Hibernate creates these itself at startup unless told not to;
-- pre-creating them here lets HAPI's database user run with CREATE SESSION only
-- (hibernate.query.mutation_strategy.global_temporary.create_tables: false in application.yaml).
--
-- GENERATED from a running schema with dbms_metadata (2026-10-08), schema qualifier removed.
-- Regenerate when the HAPI/Hibernate version changes: the set of tables and columns follows
-- the mapped entities. Loaded by db/sql/20-fhir-user.sql after oracle.sql, as SYS with
-- current_schema set to the HAPI user.

CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_BLK_EXPORT_COLFILE"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"COLLECTION_PID" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"RES_ID" VARCHAR2(100 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_BLK_EXPORT_COLLECTION"
   (	"OPTLOCK" NUMBER(10,0),
	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"JOB_PID" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"RES_TYPE" VARCHAR2(40 CHAR),
	"TYPE_FILTER" VARCHAR2(1000 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_BLK_EXPORT_JOB"
   (	"OPTLOCK" NUMBER(10,0),
	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"CREATED_TIME" TIMESTAMP (6),
	"EXP_SINCE" TIMESTAMP (6),
	"EXP_TIME" TIMESTAMP (6),
	"PID" NUMBER(19,0),
	"STATUS_TIME" TIMESTAMP (6),
	"JOB_STATUS" VARCHAR2(10 CHAR),
	"JOB_ID" VARCHAR2(36 CHAR),
	"STATUS_MESSAGE" VARCHAR2(500 CHAR),
	"REQUEST" VARCHAR2(1024 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_BLK_IMPORT_JOB"
   (	"BATCH_SIZE" NUMBER(10,0),
	"FILE_COUNT" NUMBER(10,0),
	"OPTLOCK" NUMBER(10,0),
	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"PID" NUMBER(19,0),
	"STATUS_TIME" TIMESTAMP (6),
	"JOB_STATUS" VARCHAR2(10 CHAR),
	"ROW_PROCESSING_MODE" VARCHAR2(20 CHAR),
	"JOB_ID" VARCHAR2(36 CHAR),
	"JOB_DESC" VARCHAR2(500 CHAR),
	"STATUS_MESSAGE" VARCHAR2(500 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_BLK_IMPORT_JOBFILE"
   (	"FILE_SEQ" NUMBER(10,0),
	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"JOB_PID" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"TENANT_NAME" VARCHAR2(200 CHAR),
	"FILE_DESCRIPTION" VARCHAR2(500 CHAR),
	"JOB_CONTENTS" BLOB,
	"JOB_CONTENTS_VC" CLOB,
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_RES_REINDEX_JOB"
   (	"JOB_DELETED" NUMBER(1,0),
	"REINDEX_COUNT" NUMBER(10,0),
	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"PID" NUMBER(19,0),
	"SUSPENDED_UNTIL" TIMESTAMP (6),
	"UPDATE_THRESHOLD_HIGH" TIMESTAMP (6),
	"UPDATE_THRESHOLD_LOW" TIMESTAMP (6),
	"RES_TYPE" VARCHAR2(100 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_REVINFO"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"REV" NUMBER(19,0),
	"REVTSTMP" TIMESTAMP (6),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_SEARCH"
   (	"FAILURE_CODE" NUMBER(10,0),
	"NUM_BLOCKED" NUMBER(10,0),
	"NUM_FOUND" NUMBER(10,0),
	"OPTLOCK_VERSION" NUMBER(10,0),
	"PREFERRED_PAGE_SIZE" NUMBER(10,0),
	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"SEARCH_DELETED" NUMBER(1,0),
	"SEARCH_QUERY_STRING_HASH" NUMBER(10,0),
	"SEARCH_TYPE" NUMBER(10,0),
	"TOTAL_COUNT" NUMBER(10,0),
	"CREATED" TIMESTAMP (6),
	"EXPIRY_OR_NULL" TIMESTAMP (6),
	"LAST_UPDATED_HIGH" TIMESTAMP (6),
	"LAST_UPDATED_LOW" TIMESTAMP (6),
	"PID" NUMBER(19,0),
	"RESOURCE_ID" NUMBER(19,0),
	"SEARCH_STATUS" VARCHAR2(10 CHAR),
	"SEARCH_UUID" VARCHAR2(48 CHAR),
	"RESOURCE_TYPE" VARCHAR2(200 CHAR),
	"FAILURE_MESSAGE" VARCHAR2(500 CHAR),
	"SEARCH_PARAM_MAP" BLOB,
	"SEARCH_PARAM_MAP_BIN" BLOB,
	"SEARCH_QUERY_STRING" CLOB,
	"SEARCH_QUERY_STRING_VC" CLOB,
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_SEARCH_RESULT"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"SEARCH_ORDER" NUMBER(10,0),
	"PID" NUMBER(19,0),
	"RESOURCE_PID" NUMBER(19,0),
	"SEARCH_PID" NUMBER(19,0),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_HFJ_TAG_DEF"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"TAG_TYPE" NUMBER(10,0),
	"TAG_USER_SELECTED" NUMBER(1,0),
	"TAG_ID" NUMBER(19,0),
	"TAG_VERSION" VARCHAR2(30 CHAR),
	"TAG_CODE" VARCHAR2(200 CHAR),
	"TAG_DISPLAY" VARCHAR2(200 CHAR),
	"TAG_SYSTEM" VARCHAR2(200 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_NPM_PACKAGE"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"PID" NUMBER(19,0),
	"UPDATED_TIME" TIMESTAMP (6),
	"CUR_VERSION_ID" VARCHAR2(200 CHAR),
	"PACKAGE_DESC" VARCHAR2(200 CHAR),
	"PACKAGE_ID" VARCHAR2(200 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_NPM_PACKAGE_VER"
   (	"CURRENT_VERSION" NUMBER(1,0),
	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"BINARY_RES_ID" NUMBER(19,0),
	"PACKAGE_PID" NUMBER(19,0),
	"PACKAGE_SIZE_BYTES" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"SAVED_TIME" TIMESTAMP (6),
	"UPDATED_TIME" TIMESTAMP (6),
	"FHIR_VERSION" VARCHAR2(10 CHAR),
	"FHIR_VERSION_ID" VARCHAR2(20 CHAR),
	"DESC_UPPER" VARCHAR2(200 CHAR),
	"PACKAGE_ID" VARCHAR2(200 CHAR),
	"PKG_DESC" VARCHAR2(200 CHAR),
	"VERSION_ID" VARCHAR2(200 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_NPM_PACKAGE_VER_RES"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"BINARY_RES_ID" NUMBER(19,0),
	"PACKVER_PID" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"RES_SIZE_BYTES" NUMBER(19,0),
	"UPDATED_TIME" TIMESTAMP (6),
	"FHIR_VERSION" VARCHAR2(10 CHAR),
	"FHIR_VERSION_ID" VARCHAR2(20 CHAR),
	"RES_TYPE" VARCHAR2(40 CHAR),
	"CANONICAL_URL" VARCHAR2(200 CHAR),
	"CANONICAL_VERSION" VARCHAR2(200 CHAR),
	"FILE_DIR" VARCHAR2(200 CHAR),
	"FILE_NAME" VARCHAR2(200 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_TRM_CONCEPT_DESIG"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"CONCEPT_PID" NUMBER(19,0),
	"CS_VER_PID" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"LANG" VARCHAR2(500 CHAR),
	"USE_CODE" VARCHAR2(500 CHAR),
	"USE_DISPLAY" VARCHAR2(500 CHAR),
	"USE_SYSTEM" VARCHAR2(500 CHAR),
	"VAL" VARCHAR2(2000 CHAR),
	"VAL_VC" CLOB,
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_TRM_CONCEPT_MAP_GROUP"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"CONCEPT_MAP_PID" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"CONCEPT_MAP_URL" VARCHAR2(200 CHAR),
	"SOURCE_URL" VARCHAR2(200 CHAR),
	"SOURCE_VERSION" VARCHAR2(200 CHAR),
	"SOURCE_VS" VARCHAR2(200 CHAR),
	"TARGET_URL" VARCHAR2(200 CHAR),
	"TARGET_VERSION" VARCHAR2(200 CHAR),
	"TARGET_VS" VARCHAR2(200 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_TRM_CONCEPT_MAP_GRP_ELEMENT"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"CONCEPT_MAP_GROUP_PID" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"CONCEPT_MAP_URL" VARCHAR2(200 CHAR),
	"SYSTEM_URL" VARCHAR2(200 CHAR),
	"SYSTEM_VERSION" VARCHAR2(200 CHAR),
	"VALUESET_URL" VARCHAR2(200 CHAR),
	"SOURCE_CODE" VARCHAR2(500 CHAR),
	"SOURCE_DISPLAY" VARCHAR2(500 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_TRM_CONCEPT_MAP_GRP_ELM_TGT"
   (	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"CONCEPT_MAP_GRP_ELM_PID" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"TARGET_EQUIVALENCE" VARCHAR2(50 CHAR),
	"CONCEPT_MAP_URL" VARCHAR2(200 CHAR),
	"SYSTEM_URL" VARCHAR2(200 CHAR),
	"SYSTEM_VERSION" VARCHAR2(200 CHAR),
	"VALUESET_URL" VARCHAR2(200 CHAR),
	"TARGET_CODE" VARCHAR2(500 CHAR),
	"TARGET_DISPLAY" VARCHAR2(500 CHAR),
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
CREATE GLOBAL TEMPORARY TABLE "HTE_TRM_CONCEPT_PROPERTY"
   (	"PROP_TYPE" NUMBER(10,0),
	"RN_" NUMBER(10,0) NOT NULL ENABLE,
	"CONCEPT_PID" NUMBER(19,0),
	"CS_VER_PID" NUMBER(19,0),
	"PID" NUMBER(19,0),
	"PROP_CODESYSTEM" VARCHAR2(500 CHAR),
	"PROP_DISPLAY" VARCHAR2(500 CHAR),
	"PROP_KEY" VARCHAR2(500 CHAR),
	"PROP_VAL" VARCHAR2(500 CHAR),
	"PROP_VAL_BIN" BLOB,
	"PROP_VAL_LOB" BLOB,
	 PRIMARY KEY ("RN_") ENABLE
   ) ON COMMIT DELETE ROWS;
